/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Admin": {
      "type": "sst.aws.React"
      "url": string
    }
    "DLQ": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "GetExhibitions": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "OPENAI_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Postgres": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "Producer": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "ScraperQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "Vpc": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}